### PR TITLE
Update quick start guide's complex query.

### PR DESCRIPTION
**Pull request by Friss**
Allows the code to be used without errors.

### CODE REVIEW

**Comment by spalger** [comment]
I'm not opposed to using the `request.params` syntax vs the deprecated `request.param()` helper, but I don't understand the rest of the changes. It also looks like there is a [syntax error](https://github.com/Friss/elasticsearch-js/blob/update-quick-start/docs/quick_start.asciidoc#more-complex-filtered-query) in one of the params.

**Comment by spalger** [comment]
Also, I see that you have signed the CLA. thank you

**Comment by Friss** [comment]
@spalger Ah missed a `'` when removing the old params. 

The other changes are 

* Adding in a missing `}` before the callback function
* Renaming the ES response variables to avoid a potential clash with Express's variables. (`request`, `response` for Express and `err` and `res` for ES).

**Comment by spalger** [comment]
Thanks :)

**Pull request merged**
