### PR TITLE
Always send Content-Length header. Fixes compatibility issues with el…

### PR DESCRIPTION
**Pull request by saschagoebel**
…asticsearch behind nginx.

See https://github.com/elastic/cookbook-elasticsearch/issues/38 or http://serverfault.com/questions/164220/is-there-a-way-to-avoid-nginx-411-content-length-required-errors

### CODE REVIEW

**Comment by spalger** [comment]
I see you've signed the CLA. Thanks

**Comment by spalger** [comment]
Manual check verifies that you have signed the CLA, but would you mind getting the tests passing?

**Comment by saschagoebel** [comment]
Hi,

at first I'll have to get the tests running ;-) But yes, I'll give it a go soon-ish (y)

**Comment by saschagoebel** [comment]
Here ya go!

**Comment by spalger** [comment]
Awesome :) thanks!

**Pull request merged**
