### PR TITLE
deprecate percolate and correct/remove dead percolator links

### LINKED ISSUE #469: percolate 5.x
Im trying to wrap my head around the percolator in 5.x, so forgive me if I'm totally wrong, but has the percolator API been updated in this library to match ES 5.x?  Seems like a few things are missing, like `document_type` and `field`.

If not, I'd love to help, just thought I'd ask before diving in.

### PR DESCRIPTION
**Pull request by roelandvanbatenburg**
Closes #469

- added depreciation to percolator functions in 5.x
- corrected percolator links in 5.x
- removed percolator links in 6.x

### CODE REVIEW

**Comment by spalger** [comment]
Thanks for the contribution @roelandvanbatenburg, but the APIs are actually generated from the [rest-api-spec](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api) defined in the Elasticsearch repository, so any changes should be done there. Would you mind resubmitting your changes in two PRs, one to the [5.6 version of the spec](https://github.com/elastic/elasticsearch/tree/5.6/rest-api-spec/src/main/resources/rest-api-spec/api) and one to the [6.x version of the spec](https://github.com/elastic/elasticsearch/tree/6.x/rest-api-spec/src/main/resources/rest-api-spec/api)?

**Comment by roelandvanbatenburg** [comment]
@spalger sure like this ⬆️ ?

**Comment by roelandvanbatenburg** [comment]
@spalger I can't find where the text for https://github.com/elastic/elasticsearch-js/pull/713/files#diff-c8cefc06ace53a4a974417e0d69af6d4L624 is defined. Are you sure these files origin from the elasticsearch repo?

**Comment by spalger** [comment]
Ah, those descriptions are actually defined in https://github.com/elastic/elasticsearch-js/blob/277d33715c45d7f8f2c0ad09f08136cf6ef12cea/docs/_descriptions/explain.asciidoc. If you delete that file and then regenerate the api with `node scripts/generate` that text will be removed.

**Pull request closed without merging**
