### PR TITLE
fix(TransportRequestPromise): add finally method to TransportRequestP…

### PR DESCRIPTION
**Pull request by yahiakr**
Closes: #1393

### CODE REVIEW

**Review by delvedor — CHANGES_REQUESTED** [review]
Hello! Thank you for sending a pr :)
Unfortunately, this change won't fix the issue, as you are changing only the type definition and not the original JavaScript code.

I think the best way to address this issue is to extend from `PromiseLike<T>` and add the catch definition inside the `TransportRequestPromise` interface.

**Comment by yahiakr** [comment]
Hello @delvedor!

Thanks for your response & your guidance.
I fixed it. I’m adding the tests.

I will let you know once I complete it.

**Comment by delvedor** [comment]
jenkins run the tests please

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by delvedor** [comment]
jenkins run the tests please

**Pull request merged**
