### PR TITLE
fix: keep track of indexSlice explicitly in bulk helper response handling loop

### PR DESCRIPTION
**Pull request by karlriis**
Closes https://github.com/elastic/elasticsearch-js/issues/1751

Fixes the aforementioned issue where a bulk helper call can return wrong information about the erroring operation/document via `onDrop()`, or cause a deserialization error when the request contains a delete action combined with any other action.

The fix is to keep track of `indexSlice` separately in the response handling loop of the `tryBulk` method, instead of deriving it based on the loop counter. The previous approach didn't account for different types of operations which were handled in previous iterations of the loop.

### CODE REVIEW

**Comment by karlriis** [comment]
@JoshMock Thanks, rebased against latest main now

**Comment by JoshMock** [comment]
jenkins test this

**Comment by JoshMock** [comment]
buildkite test this

**Comment by abendi** [comment]
@JoshMock any updates on getting this over the line?

**Review by JoshMock — APPROVED** [review]
Sorry for the delay @karlriis! This looks right. Merging, and will add a test to verify the change. :sunglasses:

**Comment by JoshMock** [comment]
jenkins test this

**Comment by JoshMock** [comment]
Tests are failing on Node 14.x for unrelated reasons that I can fix elsewhere. (14.x is also EOL but we'll address that in https://github.com/elastic/elasticsearch-js/issues/1855.)

**Pull request merged**
