### PR TITLE
add build badge

### PR DESCRIPTION
**Pull request by a0viedo**

### CODE REVIEW

**Comment by spalger** [comment]
Thanks for the pull request, can you please sign the CLA so I can review your changes?

**Comment by a0viedo** [comment]
hey @spalger, thanks for the heads up. Just signed the CLA, is there a way to fire again the check on GitHub?

**Comment by spalger** [comment]
Looks like it was picked up! Now that I've looked at the code... We actually don't use travis anymore. We've moved over to an elastic-managed Jenkins instance so that we can better integrate with our other systems. Thanks though!

**Comment by spalger** [comment]
I think there is a way to get the test status from Jenkins in badge form though, I'd be interested in a solution like that!

**Pull request closed without merging**
