### PR TITLE
fix keep alive timeout for agentkeepalive 2.x

### PR DESCRIPTION
**Pull request by shaharmor**
fixes https://github.com/elastic/elasticsearch-js/issues/582
fixes https://github.com/elastic/elasticsearch-js/issues/521

### CODE REVIEW

**Comment by shaharmor** [comment]
Can anyone take a look at this please?

**Comment by hathija** [comment]
Hello,

Is this fix available on the module ? In which version ?

Thanks a lot

**Comment by shaharmor** [comment]
Anyone from ES can take a look?

**Comment by alexrayan** [comment]
@spalger Hi Spencer, how are you? Could you please take a look at this pull request if you have time or point to the correct person? Thank you in advance!

**Comment by shaharmor** [comment]
Is there a reason why no one from the ES team is taking a look at this?

**Comment by rpedela** [comment]
This fixes the socket hang up problem for me when doing a large bulk request.

**Comment by rpedela** [comment]
Either the maintainers accept the PR and release a new version or you can fork, apply the fix to your fork, and use your fork in your application.

**Comment by archanid** [comment]
Sorry for the delay in looking at this or responding. We'll get on it soon.

**Comment by spalger** [comment]
Sorry for the delay folks, will be releasing this today

**Pull request merged**
