### PR TITLE
Fix hang in bulk helper semaphore when server responses are slower than flushInterval

### PR DESCRIPTION
**Pull request by JoshMock**
A possible fix for https://github.com/elastic/elasticsearch-js/issues/1562.

The failing state in the above issue is reached when a server's response times are slower than `flushInterval`. What happens in this situation, in this order:

1. The [`flushBytes` block](https://github.com/elastic/elasticsearch-js/blob/65580b0a2d59179ea9d63be315051588d0b25ab1/src/helpers.ts#L649-L655) awaits `semaphore()`
2. While awaiting, `onFlushTimeout` is triggered
3. [`onFlushTimeout` "steals"](https://github.com/elastic/elasticsearch-js/blob/65580b0a2d59179ea9d63be315051588d0b25ab1/src/helpers.ts#L684-L690) the bulk body rows that the `flushBytes` block is waiting to send by emptying `bulkBody` before awaiting a semaphore
4. When the `flushBytes` block's semaphore resolves, it tries to `send(bulkBody)` but `bulkBody` is empty

By having `flushBytes` set its blocks aside before awaiting the semaphore, like `onFlushTimeout` already does, it appears to solve the situation where a Promise sits unresolved indefinitely.

@delvedor I'm particularly interested in your thoughts on this solution, since you wrote the helper and chose the semaphore strategy.

### CODE REVIEW

**Comment by JoshMock** [comment]
I've published this to npm as `@elastic/elasticsearch-canary@8.10.1-canary.1` so that it can be tested by a few affected people.

**Review by pquentin — DISMISSED** [review]
Your explanation makes sense, but I'm unable to map it back to the code, sorry.

**Comment by JoshMock** [comment]
@pquentin Thanks. :black_heart: Mostly tagged dynamic clients team members for visibility because this bug came up in conversation in our Monday team meeting.

It still bends my mind a bit, too, and I can't find a clear explanation for why an empty `bulkBody` causes the promise to not resolve. But that's a relatively small gap to jump, especially when the fix does solve the problem in every scenario I've been able to recreate. :laughing:

**Review by alkozayMoein — APPROVED** [review]

**Review by ezimuel — DISMISSED** [review]
The solution proposed to store the `bulkBody` before the `await semaphore()` makes sense.  I'm wondering if the issue came because of the [slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) usage, since it's create a shallow copy of the array.

**Review by pquentin — APPROVED** [review]

**Pull request merged**
