### PR TITLE
[promise] swap out promise-js

### PR DESCRIPTION
**Pull request by spalger**
due to https://github.com/elastic/elasticsearch-js/issues/345 we can't use promise-js. This replaces it with npm's `promise/lib/es6-extensions` which provides a bare-bones implementation with just the es6 extensions and doesn't pollute global anything.

### CODE REVIEW

**Comment by satazor** [comment]
This would be awesome.. I've just hit another issue with `promise-js`, see. https://github.com/kevincennis/promise/issues/2

**Comment by spalger** [comment]
jenkins, test it

**Comment by spalger** [comment]
jenkins, test it

**Comment by spalger** [comment]
jenkins, test it

**Pull request merged**
