### PR TITLE
Fix issue; node roles are defaulting to true when undefined (false) breaking usage of nodeFilter option

### PR DESCRIPTION
**Pull request by deuscapturus**
nodeFilter option was unable to filter nodes where master, data or ingest roles were false because they were defaulting to true when not set.

The example below demonstrates the problem:
```
// roles are returned from the elastic API as a list
roleslist = ['master', 'ingest']
console.log(roleslist)

// The client converts the list to a dictionary
const roles = roleslist.reduce((acc,role) => { acc[role] = true; return acc}, {})
console.log(roles)

// The client then assigns default values to undefined roles
console.log(
        Object.assign({'data': true, 'master': true, 'injest': true, 'ml': false}, roles)
)

```

Output:
```
[ 'master', 'ingest' ]
{ master: true, ingest: true }
{ data: true, master: true, injest: true, ml: false, ingest: true }
```
data is `true` when it should be `false`.

### CODE REVIEW

**Comment by deuscapturus** [comment]
tests added

**Comment by deuscapturus** [comment]
oops.  I hijacked another test.  Let me try something different...

**Comment by delvedor** [comment]
jenkins run the tests please

**Comment by niksrc** [comment]
@delvedor any reason this change is not released for @elastic/elasticsearch@5 yet?

**Pull request merged**
