### PR TITLE
Fix typo in NoLivingConnectionsError

### PR DESCRIPTION
**Pull request by gomesalexandre**

### CODE REVIEW

**Comment by delvedor** [comment]
jenkins run the tests please

**Comment by gomesalexandre** [comment]
Rebased master

**Comment by delvedor** [comment]
Sorry, forgot to mention, can you sign the [CLA](https://www.elastic.co/contributor-agreement)? Thanks!

**Comment by gomesalexandre** [comment]
> Sorry, forgot to mention, can you sign the [CLA](https://www.elastic.co/contributor-agreement)? Thanks!

I already did!

**Comment by delvedor** [comment]
@gomesalexandre, unfortunately, the CLA checkers still fails, are you sure you have used the same email of you Git configuration?

**Comment by gomesalexandre** [comment]
> @gomesalexandre, unfortunately, the CLA checkers still fails, are you sure you have used the same email of you Git configuration?

It might be, signed it again !

**Comment by gomesalexandre** [comment]
travis re-test?

**Comment by delvedor** [comment]
jenkins run the tests please

**Pull request merged**
