### PR TITLE
Adding missing comma

### PR DESCRIPTION
**Pull request by ycombinator**

### CODE REVIEW

**Comment by spalger** [comment]
Thanks @ycombinator, can you apply these changes to the [examples source](https://github.com/elastic/elasticsearch-js/blob/master/docs/_examples/msearch.asciidoc) and regenerate the docs please?

**Comment by ycombinator** [comment]
@spalger I've never messed with the docs before. Should I *only* apply this change to the example doc or is that in *addition* to the change I've already made?

**Comment by spalger** [comment]
If you apply it to the example file, and then run `npm run generate` it will rebuild the file that you changed here with the updated example (as well as the other doc pages using that example)

**Comment by ycombinator** [comment]
@spalger Thanks. I did as you said but I'm afraid the generated artifacts include things unrelated to my simple typo fix. Is this expected?

**Comment by spalger** [comment]
Well, yes and no. The generate command updates the API as well as the docs, but it looks like some of the automatic updates don't regenerate nicely (specifically the snapshot.create method).

If you wouldn't mind just pushing the updated doc files that would be appreciated.

**Comment by ycombinator** [comment]
@spalger Done; this looks much better. Would you like me to squash my commits for a cleaner history?

**Comment by spalger** [comment]
No need :) I like an accurate history!

**Pull request merged**
