### PR TITLE
Fix typo in documents (example query)

### PR DESCRIPTION
**Pull request by joeyfreund**
Fix typo in example query (on [this page](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/reindex_examples.html)).
We want to match all documents where `house=stark`, not where `character=stark`.

### CODE REVIEW

**Review by JoshMock — DISMISSED** [review]
Nice catch.

Please sign that CLA and I'll get this merged ASAP. :pray:

**Comment by joeyfreund** [comment]
@JoshMock , thanks for reviewing.

I signed the CLA when I first opened the PR, and I signed it again just now. 
Do I need to do anything else in order to get the automatic CLA check to be 🍏 ?

**Comment by JoshMock** [comment]
I just noticed this PR is targeting the 8.13 branch. Can you actually point it at `main` and I'll backport it to the relevant branches?

**Comment by joeyfreund** [comment]
@JoshMock , I'm closing this PR in favour of https://github.com/elastic/elasticsearch-js/pull/2271
Can you please 🍏  and merge that one? Thanks 🙏

**Pull request closed without merging**
