### PR TITLE
Update basic-config.asciidoc

### PR DESCRIPTION
**Pull request by nicoandmee**
fix missing comma

Just fixing a missing comma 😅

### CODE REVIEW

**Review by JoshMock — APPROVED** [review]
Thanks for contribution @nicoandmee! All contributions are helpful, large or small. :slightly_smiling_face: 

Please do sign that CLA mentioned below so we can get this merged. :pray:

**Comment by nicoandmee** [comment]
> @nicoandmee I also noticed you were targeting the 8.6 branch so I changed to merge into `main`. Can you rebase your branch and sign that CLA and I'll merge this for you.

Hi! I have now done so. For some reason the CLA didn't take the first time 🤷 
Cheers

**Comment by JoshMock** [comment]
jenkins test this

**Comment by JoshMock** [comment]
Thanks again for your contribution, @nicoandmee.

**Pull request merged**
